### ISSUE TITLE
Machine Hull resource duplication

### ISSUE THREAD

**Issue by DBotThePony** [Trinsdar/GTC-Expansion#22]
**To Reproduce**

![javaw_dQtak1dicT](https://user-images.githubusercontent.com/6339511/83331391-4a2b6580-a2c0-11ea-8ad3-ad39473d236f.png)
![javaw_lQFgcpmtO5](https://user-images.githubusercontent.com/6339511/83331394-4bf52900-a2c0-11ea-851a-88074f65dd3f.png)
Same thing goes to all machine hulls

**Expected behavior**

I get 6 plates (or ingots, if you prefer) back instead of 8

**Environment**
 - Mod version: 0.1.1
 - Forge: Build 2854

**Comment by Trinsdar** [comment]
Oops, forgot about the assembling machine recipe

**Comment by YuRaNnNzZZ** [comment]
Can it also be a furnace recipe instead of crafting table one?
![javaw_2020-05-30_18-10-10](https://user-images.githubusercontent.com/5104603/83331793-dded3980-a2a0-11ea-8923-b66771f068bc.png)
![javaw_2020-05-30_18-11-08](https://user-images.githubusercontent.com/5104603/83331834-f65d5400-a2a0-11ea-8be0-31a263a258c2.png)
![javaw_2020-05-30_18-11-12](https://user-images.githubusercontent.com/5104603/83331838-f8271780-a2a0-11ea-99e3-cf3fd461061b.png)

**Comment by Trinsdar** [comment]
Yah i can do that
